pwa_firebase.settings:
  type: config_object
  label: 'Firebase settings'
  mapping:
    firebase_endpoint:
      type: string
      label: 'Firebase endpoint'
    firebase_server_key:
      type: string
      label: 'Firebase server key'
    firebase_sender_id:
      type: string
      label: 'Firebase sender ID'
    firebase_project_id:
      type: string
      label: 'Firebase project id'
    firebase_apiKey_id:
      type: string
      label: 'Firebase API Key'
    firebase_app_id:
      type: string
      label: 'Firebase app Key'
    firebase_vap_id:
      type: string
      label: 'Web Push certificates'
    firebase_measurement_id:
      type: string
      label: 'Firebase analytics'
    firebase_version:
      type: string
      label: 'Firebase version'
    firebase_enable_authorized:
      type: boolean
      label: 'Use only with authorized user'
    firebase_message_id:
      type: string
      label: 'Custom selector of div that display notification'
dependencies:
  module:
    - pwa_firebase
  enforced:
    module:
      - pwa_firebase
