# Schema for the configuration files of the Sms message module.
sms_message.settings:
  type: config_object
  label: 'Sms message settings'
  mapping:
    token:
      type: string
      label: 'token'

action.configuration.sms_message_sent_action:
  type: action_configuration_default
  label: 'Mark sent sms'

action.configuration.sms_message_unsent_action:
  type: action_configuration_default
  label: 'Mark unset sms'
