<?php

/**
 * @file
 * Provides a sms message entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sms_message_theme() {
  return [
    'sms_message' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for sms message templates.
 *
 * Default template: sms-message.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the sms message information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sms_message(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sms_message_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish sms messages.
      $storage = \Drupal::entityTypeManager()->getStorage('sms_message');
      $sms_message_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($sms_message_ids) as $sms_message) {
        $sms_message->set('status', FALSE);
        $sms_message->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize sms messages.
      $storage = \Drupal::entityTypeManager()->getStorage('sms_message');
      $sms_message_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($sms_message_ids) as $sms_message) {
        $sms_message->setOwnerId(0);
        $sms_message->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sms_message_user_predelete(UserInterface $account) {
  // Delete sms messages.
  $storage = \Drupal::entityTypeManager()->getStorage('sms_message');
  $sms_message_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $sms_messages = $storage->loadMultiple($sms_message_ids);
  $storage->delete($sms_messages);
}
