/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.color = {
    attach: function attach(context, settings) {
      $('.text-color-picker').farbtastic('#edit-popup-text-color');
      $('.bg-color-picker').farbtastic('#edit-popup-bg-color');
    }
  };
})(jQuery, Drupal);
