<?php

/**
 * @file
 * Primary module hooks for Views data export phpspreadsheet module.
 */

/**
 * Implements hook_help().
 */
function views_data_export_phpspreadsheet_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views export xlxs.
    case 'help.page.views_data_export_phpspreadsheet':
      return '<p>' . t('This module provides formats xlxs for views: For a full description of the module visit: <a href="https://www.drupal.org/project/views_data_export_phpspreadsheet">Data export phpspreadsheet</a>');
    default:
      break;
  }
}
