# Schema for the configuration files of the Shutdown module.

shutdown.settings:
  type: mapping
  label: 'Shutdown settings'
  mapping:
    shutdown_enable:
      type: integer
      label: 'Shutdown state'
    shutdown_redirect_page:
      type: string
      label: 'The path/URL where users should be redirected'
    shutdown_excluded_paths:
      type: string
      label: 'Internal paths to be excluded from the shutdown'
    shutdown_allow_http_cron:
      type: integer
      label: 'Wether to allow HTTP cron calls'
